name: dxvk artifacts arm64ec

on:
  workflow_dispatch:

jobs:
  build-dxvk:
    runs-on: ubuntu-latest

    steps:
    - name: Clone dxvk repo
      uses: actions/checkout@v4
      with:
        repository: DevikinD/dxvk
        submodules: recursive
        path: dxvk

    - name: Install llvm-mingw
      run: |
        sudo mkdir -p /opt
        curl -L -o llvm-mingw.tar.xz \
          https://github.com/bylaws/llvm-mingw/releases/download/20250305/llvm-mingw-20250305-ucrt-ubuntu-20.04-x86_64.tar.xz
        sudo tar -xvf llvm-mingw.tar.xz -C /opt/
        echo "PATH=/opt/llvm-mingw-20250305-ucrt-ubuntu-20.04-x86_64/bin:$PATH" >> $GITHUB_ENV

    - name: install dep
      run: sudo apt install meson glslang-tools
    
    - name: Build dxvk-arm64ec
      working-directory: dxvk
      run: |
        mkdir -p outputs
        ./package-release.sh master outputs --64-only

    - name: change name
      working-directory: dxvk/outputs
      run: tar -xzf dxvk-master.tar.gz && mv dxvk-master dxvk-master_arm64ec && tar -czf dxvk-master_arm64ec.tar.gz dxvk-master_arm64ec

    - name: Upload to Release
      if: success()
      uses: softprops/action-gh-release@v2
      with:
        tag_name: dxvk-build
        files: dxvk/outputs/dxvk-master_arm64ec.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
